import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Hero } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bridge Pass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
      </main>
    </>
  );
}
